### ISSUE TITLE
docs.rs build failed 

### ISSUE THREAD

**Issue by Shoeboxam** [opendp/opendp#1328] opened 2024-02-27 09:09 UTC
Build in question:
https://docs.rs/crate/opendp/0.9.2/builds/1120302

I think we just need to double-check that the features are configured in such a way, by default, that file writes aren't happening. We must be triggering the write for cbindgen still?

**Comment by mccalluc** [comment] 2024-03-29 13:33
nightly builds on docs.rs are now passing

- duplicate of #1414
- fixed by #1434

Note that because our convention is to add a suffix to the previous release, rather than the upcoming release, that page still has a warning.
- See also #1435

**Closed by mccalluc** 2024-03-29 13:33 UTC
