### ISSUE TITLE
`histograms.ipynb` fails on Binder

### ISSUE THREAD

**Issue by andrewvyrros** [opendp/opendp#606] opened 2022-11-03 18:36 UTC
Example notebook `histograms.ipynb` (and presumably others) doesn't work on Binder because it needs `matplotlib`. I believe there's a config file we can drop somewhere for dependencies.

**Comment by Shoeboxam** [comment] 2022-11-03 18:37
Config file located here: https://github.com/opendp/opendp/tree/main/.binder

**Comment by Shoeboxam** [comment] 2022-11-03 18:39
I wonder if it could just contain `-r ../docs/requirements_notebooks.txt`?

**Comment by mccalluc** [comment] 2023-08-21 02:58
- Issue #903 was essentially a duplicate of this
- PR #910 fixed it [by adding `-r ../docs/requirements_notebooks.txt`](https://github.com/opendp/opendp/pull/910/files#diff-7027aa145ff352398f38b1cdccf34168731f4bd060315d3e3c4512bc9268dcb2), as you suggested above.

This can probably be closed?

**Comment by Shoeboxam** [comment] 2023-10-12 18:08
Thanks for noticing the dupe @mccalluc!

**Closed by Shoeboxam** 2023-10-12 18:08 UTC
Labels: Effort 1 - Small :coffee:
